[package]
name = "ubuntu-distro-info"
version = "0.1.0"
authors = ["Daniel Watkins <daniel@daniel-watkins.co.uk>"]

[dependencies]
distro-info = { path = "../" }
chrono = "0.4.3"
clap = "2.31.2"
failure = "0.1.1"
