name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: "distro-info-rs: Build"
      run: cargo build --verbose
    - name: "distro-info-rs: Run cargo test"
      run: cargo test --verbose

    - name: "binaries: Build"
      run: cd binaries && cargo build --verbose
    - name: "binaries: Run cargo test"
      run: cd binaries && cargo test --verbose
    - name: "binaries: Upstream tests"
      run: cd tests && make ci-install-deps && make test

  coverage:

    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
    - uses: actions/checkout@v3
    - name: "distro-info-rs: Coverage"
      run: |
        cargo +nightly tarpaulin \
          --verbose \
          --exclude-files binaries/\*
